fullnameOverride: cve-kafka

sasl:
  client:
    users:
      - archops_admin
    passwords:
      - ArchOps@670951

controller:
  replicaCount: 3
  podAntiAffinityPreset: soft
  persistence:
    enabled: true
    size: 10Gi
  resources:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 0.5
      memory: 512Mi

provisioning:
  enabled: true
  podLabels:
    sidecar.istio.io/inject: "false"
  topics:
    - name: cve
      partitions: 3
      replicationFactor: 3
      config:
        min.insync.replicas: 2
        compression.type: snappy

kraft:
  enabled: true

zookeeper:
  enabled: false

rbac:
  create: true

networkPolicy:
  enabled: true
  allowExternal: false
  extraIngress:
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: cve-operator
      - podSelector:
          matchLabels:
            app: cve-processor
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: cve-processor
      - podSelector:
          matchLabels:
            app: cve-processor
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: cve-consumer
      - podSelector:
          matchLabels:
            app: cve-consumer
    - from:
      - namespaceSelector:
          matchLabels:
            kubernetes.io/metadata.name: monitoring
      - podSelector:
          matchLabels:
            release: kube-prometheus-stack

metrics:
  jmx:
    enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    labels:
      release: kube-prometheus-stack
    selector:
      app.kubernetes.io/name: kafka