apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: grafana-cert-prod
  namespace: istio-ingress
spec:
  secretName: grafana-tls-prod
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - grafana.pritesh-nimje.me
    - api.pritesh-nimje.me
