apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
  namespace: istio-system
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: more.ni@northeastern.edu
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector:
        dnsZones:
          - "pritesh-nimje.me"
      dns01:
        route53:
          region: us-east-1
          hostedZoneID: Z0151744165C9M3XQJHIG