fullnameOverride: cve-postgresql

auth:
  username: your username 
  password: your password
  database: cve
  
primary:
  podLabels:
    app: cve-postgresql
    sidecar.istio.io/inject: "false"

  persistence:
    enabled: true
    storageClass: "ebs-sc"
    accessModes:
      - ReadWriteOnce
    size: 8Gi

  resources:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 0.5
      memory: 512Mi

networkPolicy:
  enabled: true
  allowExternal: false
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              "kubernetes.io/metadata.name": cve-consumer
        - namespaceSelector:
            matchLabels:
              "kubernetes.io/metadata.name": monitoring
        - podSelector:
            matchLabels:
              app: cve-consumer
        - podSelector:
            matchLabels:
              app: prometheus
  
metrics:
  enabled: true
  serviceMonitor:
    enabled: true
    namespace: monitoring
    labels:
      release: kube-prometheus-stack  